/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, FileWrapper, RequestOptions } from '../core';
import {
  GenerateSdkViaUrlRequest,
  generateSdkViaUrlRequestSchema,
} from '../models/generateSdkViaUrlRequest';
import { Platforms, platformsSchema } from '../models/platforms';
import {
  UserCodeGeneration,
  userCodeGenerationSchema,
} from '../models/userCodeGeneration';
import { array, string } from '../schema';
import { BaseController } from './baseController';

export class CodeGenerationExternalApIsController extends BaseController {
  /**
   * Generate an SDK for an API by by uploading the API specification file.
   *
   * This endpoint generates and then uploads the generated SDK to APIMatic's cloud storage. An ID for
   * the generation performed is returned as part of the response.
   *
   * This endpoint does not import an API into APIMatic.
   *
   * @param file     The API specification file.<br>The type of the specification file should be any of
   *                                the [supported formats](https://docs.apimatic.io/api-transformer/overview-
   *                                transformer#supported-input-formats).
   * @param template The structure contains platforms that APIMatic CodeGen can generate SDKs and Docs
   *                                in.
   * @return Response from the API call
   */
  async generateSdkViaFile(
    file: FileWrapper,
    template: Platforms,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UserCodeGeneration>> {
    const req = this.createRequest(
      'POST',
      '/code-generations/generate-via-file'
    );
    const mapped = req.prepareArgs({ template: [template, platformsSchema] });
    req.formData({ file: file, template: mapped.template });
    req.authenticate([{ authorization: true }]);
    return req.callAsJson(userCodeGenerationSchema, requestOptions);
  }

  /**
   * Generate an SDK for an API by providing the URL of the API specification file.
   *
   * This endpoint generates and then uploads the generated SDK to APIMatic's cloud storage. An ID for
   * the generation performed is returned as part of the response.
   *
   * This endpoint does not import an API into APIMatic.
   *
   * @param body         Request Body
   * @return Response from the API call
   */
  async generateSdkViaUrl(
    body: GenerateSdkViaUrlRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UserCodeGeneration>> {
    const req = this.createRequest(
      'POST',
      '/code-generations/generate-via-url'
    );
    const mapped = req.prepareArgs({
      body: [body, generateSdkViaUrlRequestSchema],
    });
    req.header(
      'Content-Type',
      'application/vnd.apimatic.userCodeGenerationDto.v1+json'
    );
    req.json(mapped.body);
    req.authenticate([{ authorization: true }]);
    return req.callAsJson(userCodeGenerationSchema, requestOptions);
  }

  /**
   * Download the SDK generated via the Generate SDK endpoints.
   *
   * @param codegenId  The ID of code generation received in the response of the [Generate SDK Via
   *                             File](https://www.apimatic.io/api-docs-
   *                             preview/dashboard/60eea3b7a73395c3052d961b/v/3_0#/http/api-endpoints/code-generation-
   *                             external-apis/generate-sdk-via-file) or [Generate SDK Via URL ](https://www.apimatic.
   *                             io/api-docs-preview/dashboard/60eea3b7a73395c3052d961b/v/3_0#/http/api-endpoints/code-
   *                             generation-external-apis/generate-sdk-via-url) calls.
   * @return Response from the API call
   */
  async downloadSdk(
    codegenId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NodeJS.ReadableStream | Blob>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ codegenId: [codegenId, string()] });
    req.appendTemplatePath`/code-generations/${mapped.codegenId}/generated-sdk`;
    req.authenticate([{ authorization: true }]);
    return req.callAsStream(requestOptions);
  }

  /**
   * Get a list of all SDK generations performed with external APIs via the Generate SDK endpoints.
   *
   * @return Response from the API call
   */
  async listAllCodeGenerations(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UserCodeGeneration[]>> {
    const req = this.createRequest('GET', '/code-generations');
    req.authenticate([{ authorization: true }]);
    return req.callAsJson(array(userCodeGenerationSchema), requestOptions);
  }

  /**
   * Download the API Specification file used as input for a specific SDK generation performed via the
   * Generate SDK endpoints.
   *
   * @param codegenId  The ID of the code generation to download the API specification for. The code
   *                             generation ID is received in the response of the [Generate SDK Via File](https://www.
   *                             apimatic.io/api-docs-preview/dashboard/60eea3b7a73395c3052d961b/v/3_0#/http/api-
   *                             endpoints/code-generation-external-apis/generate-sdk-via-file) or [Generate SDK Via
   *                             URL ](https://www.apimatic.io/api-docs-
   *                             preview/dashboard/60eea3b7a73395c3052d961b/v/3_0#/http/api-endpoints/code-generation-
   *                             external-apis/generate-sdk-via-url) calls
   * @return Response from the API call
   */
  async downloadInputFile(
    codegenId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NodeJS.ReadableStream | Blob>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ codegenId: [codegenId, string()] });
    req.appendTemplatePath`/code-generations/${mapped.codegenId}/input-file`;
    req.authenticate([{ authorization: true }]);
    return req.callAsStream(requestOptions);
  }

  /**
   * Get details on an SDK generation performed for an external API via the Generate SDK endpoints.
   *
   * @param codegenId  The ID of the code generation to fetch. The code generation ID is received in the
   *                             response of the [Generate SDK Via File](https://www.apimatic.io/api-docs-
   *                             preview/dashboard/60eea3b7a73395c3052d961b/v/3_0#/http/api-endpoints/code-generation-
   *                             external-apis/generate-sdk-via-file) or [Generate SDK Via URL ](https://www.apimatic.
   *                             io/api-docs-preview/dashboard/60eea3b7a73395c3052d961b/v/3_0#/http/api-endpoints/code-
   *                             generation-external-apis/generate-sdk-via-url) calls.
   * @return Response from the API call
   */
  async getACodeGeneration(
    codegenId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UserCodeGeneration>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ codegenId: [codegenId, string()] });
    req.appendTemplatePath`/code-generations/${mapped.codegenId}`;
    req.authenticate([{ authorization: true }]);
    return req.callAsJson(userCodeGenerationSchema, requestOptions);
  }

  /**
   * Delete an SDK generation performed for an API via the Generate SDK endpoints.
   *
   * @param codegenId  The ID of the code generation to delete. The code generation ID is received in the
   *                             response of the [Generate SDK Via File](https://www.apimatic.io/api-docs-
   *                             preview/dashboard/60eea3b7a73395c3052d961b/v/3_0#/http/api-endpoints/code-generation-
   *                             external-apis/generate-sdk-via-file) or [Generate SDK Via URL ](https://www.apimatic.
   *                             io/api-docs-preview/dashboard/60eea3b7a73395c3052d961b/v/3_0#/http/api-endpoints/code-
   *                             generation-external-apis/generate-sdk-via-url) calls.
   * @return Response from the API call
   */
  async deleteCodeGeneration1(
    codegenId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ codegenId: [codegenId, string()] });
    req.appendTemplatePath`/code-generations/${mapped.codegenId}`;
    req.authenticate([{ authorization: true }]);
    return req.call(requestOptions);
  }
}
