/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Accept2
 */
export enum Accept2 {
  EnumApplicationvndapimaticapiEntityfullv1json = 'application/vnd.apimatic.apiEntity.full.v1+json',
}

/**
 * Schema for Accept2
 */
export const accept2Schema: Schema<Accept2> = stringEnum(Accept2);
