/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Accept3
 */
export enum Accept3 {
  EnumApplicationzip = 'application/zip',
}

/**
 * Schema for Accept3
 */
export const accept3Schema: Schema<Accept3> = stringEnum(Accept3);
