/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Accept
 */
export enum Accept {
  EnumApplicationjson = 'application/json',
}

/**
 * Schema for Accept
 */
export const acceptSchema: Schema<Accept> = stringEnum(Accept);
