/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface ApiValidationSummary {
  success: boolean;
  errors: string[];
  warnings: string[];
  messages: string[];
  additionalProperties?: Record<string, unknown>;
}

export const apiValidationSummarySchema: Schema<ApiValidationSummary> = typedExpandoObject(
  {
    success: ['success', boolean()],
    errors: ['errors', array(string())],
    warnings: ['warnings', array(string())],
    messages: ['messages', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
