/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** The structure contain attribute details of a parameter type. */
export interface Attributes {
  /** Unique Attribute Identifier */
  id: string;
}

export const attributesSchema: Schema<Attributes> = object({
  id: ['id', string()],
});
