/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** The structure contain attribute details of a parameter type. */
export interface Attributes {
  /** Unique Attribute Identifier */
  id: string;
  additionalProperties?: Record<string, unknown>;
}

export const attributesSchema: Schema<Attributes> = typedExpandoObject(
  { id: ['id', string()] },
  'additionalProperties',
  optional(unknown())
);
