/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface AuthScope {
  /** Scope Id */
  id: string;
  /** Scope Name */
  name: string;
  /** Scope Value */
  value: string;
  /** Scope Description */
  description: string;
  additionalProperties?: Record<string, unknown>;
}

export const authScopeSchema: Schema<AuthScope> = typedExpandoObject(
  {
    id: ['id', string()],
    name: ['name', string()],
    value: ['value', string()],
    description: ['description', string()],
  },
  'additionalProperties',
  optional(unknown())
);
