/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface AuthorIdentifiers {
  email: string;
  userName: string;
}

export const authorIdentifiersSchema: Schema<AuthorIdentifiers> = object({
  email: ['Email', string()],
  userName: ['UserName', string()],
});
