/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface AuthScope {
  /** Scope Id */
  id: string;
  /** Scope Name */
  name: string;
  /** Scope Value */
  value: string;
  /** Scope Description */
  description: string;
}

export const authScopeSchema: Schema<AuthScope> = object({
  id: ['id', string()],
  name: ['name', string()],
  value: ['value', string()],
  description: ['description', string()],
});
