/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface AuthorIdentifiers {
  email: string;
  userName: string;
  additionalProperties?: Record<string, unknown>;
}

export const authorIdentifiersSchema: Schema<AuthorIdentifiers> = typedExpandoObject(
  { email: ['Email', string()], userName: ['UserName', string()] },
  'additionalProperties',
  optional(unknown())
);
