/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ContentType
 */
export enum ContentType {
  EnumMultipartformdata = 'multipart/form-data',
}

/**
 * Schema for ContentType
 */
export const contentTypeSchema: Schema<ContentType> = stringEnum(ContentType);
