/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';
import { Id, idSchema } from './id';
import { Link, linkSchema } from './link';

/** This structure contains all details that goes into package deployment. */
export interface CSNETSTANDARDLIB {
  /** Unique package identifier */
  id?: Id;
  /** Package Repository as per platform */
  packageRepository: string;
  /** Package Name */
  packageName: string;
  version: string;
  /** Any additional platform specific deployment detail */
  additionalDeploymentInformation?: unknown;
  /** Link of deployed package */
  link?: Link;
}

export const cSNETSTANDARDLIBSchema: Schema<CSNETSTANDARDLIB> = object({
  id: ['id', optional(idSchema)],
  packageRepository: ['packageRepository', string()],
  packageName: ['packageName', string()],
  version: ['version', string()],
  additionalDeploymentInformation: [
    'additionalDeploymentInformation',
    optional(unknown()),
  ],
  link: ['link', optional(linkSchema)],
});
