/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** This structure encapsulates all the attributes of an API Endpoints Group. */
export interface EndpointsGroup {
  name: string;
  description: string;
  additionalProperties?: Record<string, unknown>;
}

export const endpointsGroupSchema: Schema<EndpointsGroup> = typedExpandoObject(
  { name: ['name', string()], description: ['description', string()] },
  'additionalProperties',
  optional(unknown())
);
