/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ExportFormats
 */
export enum ExportFormats {
  APIMATIC = 'APIMATIC',
  WADL2009 = 'WADL2009',
  WSDL = 'WSDL',
  SWAGGER10 = 'Swagger10',
  SWAGGER20 = 'Swagger20',
  SWAGGERYAML = 'SwaggerYaml',
  OAS3 = 'OpenApi3Json',
  OPENAPI3YAML = 'OpenApi3Yaml',
  APIBLUEPRINT = 'APIBluePrint',
  RAML = 'RAML',
  RAML10 = 'RAML10',
  POSTMAN10 = 'Postman10',
  POSTMAN20 = 'Postman20',
  GRAPHQLSCHEMA = 'GraphQlSchema',
}

/**
 * Schema for ExportFormats
 */
export const exportFormatsSchema: Schema<ExportFormats> = stringEnum(
  ExportFormats
);
