/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ExportFormats
 */
export enum ExportFormats {
  Apimatic = 'APIMATIC',
  Wadl2009 = 'WADL2009',
  Wsdl = 'WSDL',
  Swagger10 = 'Swagger10',
  Swagger20 = 'Swagger20',
  Swaggeryaml = 'SwaggerYaml',
  Oas3 = 'OpenApi3Json',
  Openapi3Yaml = 'OpenApi3Yaml',
  Apiblueprint = 'APIBluePrint',
  Raml = 'RAML',
  Raml10 = 'RAML10',
  Postman10 = 'Postman10',
  Postman20 = 'Postman20',
  Graphqlschema = 'GraphQlSchema',
}

/**
 * Schema for ExportFormats
 */
export const exportFormatsSchema: Schema<ExportFormats> = stringEnum(
  ExportFormats
);
