/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { Platforms, platformsSchema } from './platforms';

export interface GenerateSdkViaUrlRequest {
  /** The URL for the API specification file.<br><br>**Note:** This URL should be publicly accessible. */
  url: string;
  /** The structure contains platforms that APIMatic CodeGen can generate SDKs and Docs in. */
  template: Platforms;
}

export const generateSdkViaUrlRequestSchema: Schema<GenerateSdkViaUrlRequest> = object(
  { url: ['url', string()], template: ['template', platformsSchema] }
);
