/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Id
 */
export enum Id {
  Enum5Dcd2B5893C3E31A206F30C4 = '5dcd2b5893c3e31a206f30c4',
}

/**
 * Schema for Id
 */
export const idSchema: Schema<Id> = stringEnum(Id);
