/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ImplementationType
 */
export enum ImplementationType {
  Structure = 'Structure',
  Enumeration = 'Enumeration',
  Exception = 'Exception',
}

/**
 * Schema for ImplementationType
 */
export const implementationTypeSchema: Schema<ImplementationType> = stringEnum(
  ImplementationType
);
