/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, Schema, string } from '../schema';

export interface ImportValidationSummary {
  success: boolean;
  errors: string[];
  warnings: string[];
  messages: string[];
}

export const importValidationSummarySchema: Schema<ImportValidationSummary> = object(
  {
    success: ['success', boolean()],
    errors: ['errors', array(string())],
    warnings: ['warnings', array(string())],
    messages: ['messages', array(string())],
  }
);
