/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** This structure contains details of importing a new API Version */
export interface ImportApiVersionViaUrlRequest {
  /** The version number with which the new API version will be imported. This version number will override the version specified in the API specification file.<br>APIMatic recommends versioning the API with the [versioning scheme](https://docs.apimatic.io/define-apis/basic-settings/#version) documented in the docs. */
  versionOverride: string;
  /** The URL for the API specification file.<br><br>**Note:** This URL should be publicly accessible. */
  url: string;
}

export const importApiVersionViaUrlRequestSchema: Schema<ImportApiVersionViaUrlRequest> = object(
  { versionOverride: ['version_override', string()], url: ['url', string()] }
);
