/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

/** This structure helps specify details of an input parameter. */
export interface InputParameter {
  /** If parameter is null */
  isNull: boolean;
  /** Unique parameter identifier for each endpoint */
  endpointInputPrameterId: string;
  /** Unique parameter identifier */
  id: string;
  /** Parameter Name */
  name: string;
  /** Parameter Value */
  value: string;
}

export const inputParameterSchema: Schema<InputParameter> = object({
  isNull: ['isNull', boolean()],
  endpointInputPrameterId: ['endpointInputPrameterId', string()],
  id: ['id', string()],
  name: ['name', string()],
  value: ['value', string()],
});
