/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Links {
  status: string;
  download: string;
}

export const linksSchema: Schema<Links> = object({
  status: ['status', string()],
  download: ['download', string()],
});
