/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import {
  ApiValidationSummary,
  apiValidationSummarySchema,
} from './apiValidationSummary';
import {
  DocsValidationSummary,
  docsValidationSummarySchema,
} from './docsValidationSummary';
import {
  ImportValidationSummary,
  importValidationSummarySchema,
} from './importValidationSummary';

export interface MetaData {
  importValidationSummary: ImportValidationSummary;
  apiValidationSummary: ApiValidationSummary;
  docsValidationSummary: DocsValidationSummary;
}

export const metaDataSchema: Schema<MetaData> = object({
  importValidationSummary: [
    'importValidationSummary',
    lazy(() => importValidationSummarySchema),
  ],
  apiValidationSummary: [
    'apiValidationSummary',
    lazy(() => apiValidationSummarySchema),
  ],
  docsValidationSummary: [
    'docsValidationSummary',
    lazy(() => docsValidationSummarySchema),
  ],
});
