/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, optional, Schema, typedExpandoObject, unknown } from '../schema';
import {
  ApiValidationSummary,
  apiValidationSummarySchema,
} from './apiValidationSummary';
import {
  DocsValidationSummary,
  docsValidationSummarySchema,
} from './docsValidationSummary';
import {
  ImportValidationSummary,
  importValidationSummarySchema,
} from './importValidationSummary';

export interface MetaData {
  importValidationSummary: ImportValidationSummary;
  apiValidationSummary: ApiValidationSummary;
  docsValidationSummary: DocsValidationSummary;
  additionalProperties?: Record<string, unknown>;
}

export const metaDataSchema: Schema<MetaData> = typedExpandoObject(
  {
    importValidationSummary: [
      'importValidationSummary',
      lazy(() => importValidationSummarySchema),
    ],
    apiValidationSummary: [
      'apiValidationSummary',
      lazy(() => apiValidationSummarySchema),
    ],
    docsValidationSummary: [
      'docsValidationSummary',
      lazy(() => docsValidationSummarySchema),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
