/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Platforms
 */
export enum Platforms {
  CsNetStandardLib = 'CS_NET_STANDARD_LIB',
  JavaEclipseJreLib = 'JAVA_ECLIPSE_JRE_LIB',
  PhpGenericLibV2 = 'PHP_GENERIC_LIB_V2',
  PythonGenericLib = 'PYTHON_GENERIC_LIB',
  RubyGenericLib = 'RUBY_GENERIC_LIB',
  TsGenericLib = 'TS_GENERIC_LIB',
  GoGenericLib = 'GO_GENERIC_LIB',
}

/**
 * Schema for Platforms
 */
export const platformsSchema: Schema<Platforms> = stringEnum(Platforms);
