/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Platforms
 */
export enum Platforms {
  CSNETSTANDARDLIB = 'CS_NET_STANDARD_LIB',
  JAVAECLIPSEJRELIB = 'JAVA_ECLIPSE_JRE_LIB',
  PHPGENERICLIBV2 = 'PHP_GENERIC_LIB_V2',
  PYTHONGENERICLIB = 'PYTHON_GENERIC_LIB',
  RUBYGENERICLIB = 'RUBY_GENERIC_LIB',
  TSGENERICLIB = 'TS_GENERIC_LIB',
  GOGENERICLIB = 'GO_GENERIC_LIB',
}

/**
 * Schema for Platforms
 */
export const platformsSchema: Schema<Platforms> = stringEnum(Platforms);
