/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Status
 */
export enum Status {
  Completed = 'Completed',
  InProgress = 'InProgress',
  Failed = 'Failed',
}

/**
 * Schema for Status
 */
export const statusSchema: Schema<Status> = stringEnum(Status);
