/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, unknown } from '../schema';

/** This structure helps specify additional test configurations which affects how test cases are generated. */
export interface TestGenSettings {
  /** Error margin for comparing values in decimal places */
  precisionDelta: number;
  /** Number of seconds after which if the endpoint is not returning any response, the test is forced to fail e.g. a timeout of 60 */
  testTimeout: number;
  /** The parameters allows to provide values for configuration file for use in the test environment */
  configuration?: unknown;
}

export const testGenSettingsSchema: Schema<TestGenSettings> = object({
  precisionDelta: ['precisionDelta', number()],
  testTimeout: ['testTimeout', number()],
  configuration: ['configuration', optional(unknown())],
});
