/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { ExportFormats, exportFormatsSchema } from './exportFormats';

/** This structure puts together the URL of the file to be transformed, along with the desired export format. */
export interface TransformViaUrlRequest {
  /** The URL for the API specification file.<br><br>**Note:** This URL should be publicly accessible. */
  url: string;
  /** The structure contains API specification formats that Transformer can convert to. */
  exportFormat: ExportFormats;
  additionalProperties?: Record<string, unknown>;
}

export const transformViaUrlRequestSchema: Schema<TransformViaUrlRequest> = typedExpandoObject(
  {
    url: ['url', string()],
    exportFormat: ['export_format', exportFormatsSchema],
  },
  'additionalProperties',
  optional(unknown())
);
