/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, optional, Schema, typedExpandoObject, unknown } from '../schema';
import { Csnetstandardlib, csnetstandardlibSchema } from './csnetstandardlib';

/** This structure helps update package deployment details. */
export interface UpdateTemplatesPackageDeploymentInformation {
  /** This structure contains all details that goes into package deployment. */
  csNetStandardLib: Csnetstandardlib;
  additionalProperties?: Record<string, unknown>;
}

export const updateTemplatesPackageDeploymentInformationSchema: Schema<UpdateTemplatesPackageDeploymentInformation> = typedExpandoObject(
  {
    csNetStandardLib: [
      'CS_NET_STANDARD_LIB',
      lazy(() => csnetstandardlibSchema),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
