/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import {
  UpdateTemplatesPackageDeploymentInformation,
  updateTemplatesPackageDeploymentInformationSchema,
} from './updateTemplatesPackageDeploymentInformation';

/** This structure is used to update package deployment details. */
export interface UpdatePackageDeploymentInformation {
  /** This structure helps update package deployment details. */
  templatesPackageDeploymentInformation: UpdateTemplatesPackageDeploymentInformation;
}

export const updatePackageDeploymentInformationSchema: Schema<UpdatePackageDeploymentInformation> = object(
  {
    templatesPackageDeploymentInformation: [
      'templatesPackageDeploymentInformation',
      lazy(() => updateTemplatesPackageDeploymentInformationSchema),
    ],
  }
);
