/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Validation exception contains information, warnings, messages and errors. */
export interface ValidationException {
  reason: string;
  /** Validation Summary of the API in case validation failed */
  summary?: string;
  additionalProperties?: Record<string, unknown>;
}

export const validationExceptionSchema: Schema<ValidationException> = typedExpandoObject(
  { reason: ['reason', string()], summary: ['summary', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
