# -*- coding: utf-8 -*-

"""
    apimatic.api_matic_client

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from .decorators import lazy_property
from .configuration import Configuration
from .controllers.validator_controller import ValidatorController
from .controllers.transformer_controller import TransformerController
from .controllers.generator_controller import GeneratorController

class ApimaticClient(object):

    config = Configuration

    @lazy_property
    def validator(self):
        return ValidatorController()

    @lazy_property
    def transformer(self):
        return TransformerController()

    @lazy_property
    def generator(self):
        return GeneratorController()


    def __init__(self, 
                 authorization = None):
        if authorization != None:
            Configuration.authorization = authorization


