# -*- coding: utf-8 -*-

"""
    apimaticlib.api_matic_client

    This file was automatically generated by APIMATIC BETA v2.0 on 09/07/2016
"""

from .http import *
from .models import *
from .exceptions import *
from .decorators import *
from .controllers import *

class APIMaticClient(object):

    @lazy_property
    def validator(self):
        return ValidatorController()

    @lazy_property
    def generator(self):
        return GeneratorController()


    def __init__(self, 
                 basic_auth_user_name = None,
                 basic_auth_password = None):

        Configuration.basic_auth_user_name = basic_auth_user_name
        Configuration.basic_auth_password = basic_auth_password


