# -*- coding: utf-8 -*-

"""
   apimaticlib.configuration

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/07/2016
"""

class Configuration(object):
    # The base Uri for API calls
    BASE_URI = 'https://apimatic.io/api'

    # The username to use with basic authentication
    # TODO: Replace the basic_auth_user_name with an appropriate value
    basic_auth_user_name = "TODO: Replace"

    # The password to use with basic authentication
    # TODO: Replace the basic_auth_password with an appropriate value
    basic_auth_password = "TODO: Replace"


