/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of InternalServerErrorResponse
 */
interface InternalServerErrorResponse {
  message?: string;
  additionalProperties?: Record<string, unknown>;
}

export class InternalServerErrorResponseError extends ApiError<
  InternalServerErrorResponse
> {}
