/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PortalGenerationForbiddenResponse
 */
interface PortalGenerationForbiddenResponse {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  errors?: Record<string, unknown>;
}

export class PortalGenerationForbiddenResponseError extends ApiError<
  PortalGenerationForbiddenResponse
> {}
