/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PortalGenerationValidationErrorResponse
 */
interface PortalGenerationValidationErrorResponse {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  errors?: Record<string, unknown>;
}

export class PortalGenerationValidationErrorResponseError extends ApiError<
  PortalGenerationValidationErrorResponse
> {}
