/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of UnauthorizedResponse
 */
interface UnauthorizedResponse {
  message?: string;
  additionalProperties?: Record<string, unknown>;
}

export class UnauthorizedResponseError extends ApiError<UnauthorizedResponse> {}
