# -*- coding: utf-8 -*-

"""
   apimatic.http.auth.custom_header_auth

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

from ...configuration import Configuration

class CustomHeaderAuth:

    @staticmethod
    def apply(http_request):
        """ Add custom authentication to the request.

        Args:
            http_request (HttpRequest): The HttpRequest object to which 
                authentication will be added.

        """                
        http_request.headers["Authorization"] = Configuration.authorization
