openapi: 3.0.3
info: { title: Outside, version: 1.0.0 }
paths:
  /things:
    post:
      tags: [Things]
      operationId: CreateThing
      summary: Create thing
      requestBody:
        content:
          application/json:
            schema: { $ref: '../shared/thing.yaml' }
            examples:
              one: { summary: One, value: { a: 1 } }
      responses: { '201': { description: Created } }
