# -*- coding: utf-8 -*-

"""
    apimatic.models.validation_summary

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class ValidationSummary(object):

    """Implementation of the 'ValidationSummary' model.

    A summary of API description validation.

    Attributes:
        success (bool): TODO: type description here.
        errors (list of string): TODO: type description here.
        warnings (list of string): TODO: type description here.
        messages (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "success" : "Success",
        "errors" : "Errors",
        "warnings" : "Warnings",
        "messages" : "Messages"
    }

    def __init__(self,
                 success=None,
                 errors=None,
                 warnings=None,
                 messages=None):
        """Constructor for the ValidationSummary class"""

        # Initialize members of the class
        self.success = success
        self.errors = errors
        self.warnings = warnings
        self.messages = messages


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        success = dictionary.get("Success")
        errors = dictionary.get("Errors")
        warnings = dictionary.get("Warnings")
        messages = dictionary.get("Messages")

        # Return an object of this model
        return cls(success,
                   errors,
                   warnings,
                   messages)


