# This is a basic workflow to help you get started with Actions

name: Run and check build for current commit

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the alpha and dev branches
  pull_request:
    branches: [ alpha, dev ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '20', '22', '24' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: checkout cli
        uses: actions/checkout@v4
        with:
          repository: apimatic/apimatic-cli
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
          fetch-depth: 0
          path: cli

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: enable corepack
        run: corepack enable

      - name: configure pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: cli/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: cli
        run: pnpm install --frozen-lockfile

      - name: Check Build
        working-directory: 'cli'
        run: pnpm build
