# This is a basic workflow to help you get started with Actions

name: Run and check build for current commit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '13', '14' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: checkout cli
        uses: actions/checkout@v2
        with:
          repository: apimatic/apimatic-cli
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false
          fetch-depth: 0
          path: cli

      - name: setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        working-directory: cli
        run: |
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github.com/".insteadOf https://github.com/
          npm install

      - name: Check Build
        working-directory: 'cli'
        run: npm run build