name: Set Latest Tag

on:
  workflow_dispatch:
  push:
  
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14' ]
    name: Release with Node version ${{ matrix.node }}
    steps:
      - name: change-latest-tag
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm whoami
