name: Set Latest Tag

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Move the latest dist-tag
    steps:
      - name: change-latest-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm dist-tag add @apimatic/cli@${LATEST_VERSION} latest
